import "./globals.css";
import { AppLayout } from "@/components/layouts/AppLayout/AppLayout";
import { Inter, Noto_Serif } from 'next/font/google'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})
 
const noto_serif = Noto_Serif({
  subsets: ['latin'],
  variable: '--font-noto-serif',
  display: 'swap',
})
 

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${noto_serif.variable}`} >
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
      </head>
      <body className="bg-[#F9F6F4]">
        <AppLayout>
          {children}
        </AppLayout>
      </body>
    </html>
  );
}
